### ISSUE TITLE
Update ob-tmux default vars

### ISSUE THREAD

**Issue by hh** [ii/doom-config#3]
Ensure that the default target `:session ii:$COOPNAME` or similar is set  so it drives the right eye in our iipod / iikea cooperations. Currently it doesn't work. May also need to set the default terminal to `/bin/true` so it doesn't complain about launching one.

**Comment by zachmandeville** [comment]
I updated the vars for the default session (in PR #4).  This will use our standard default session unless the CODER_WORKSPACE_NAME env var is present, in which case it'll use this.

However, the windows are not operating well for me, and I think it is due to the actual ob-tmate code and changes we've made to it.  From my understanding, we define a window parameter and set it when [creating ob-tmate sessions](https://github.com/humacs/ii-pair/blob/main/ii-ob-tmate.el#L152-L155), however the code that actually creates the window
or check if the window exists does not use this parameter(see [ob-window-alive](https://github.com/humacs/ii-pair/blob/main/ii-ob-tmate.el#L547)

Instead, it still pulls the window name from the session as is designed in the original ob-tmate.  In the [orignal ob-tmate](https://github.com/ii/ob-tmate), the window is parsed from the session var:
```
#+BEGIN_SRC tmate :session hello:new-window
echo hello world in new-window
#+END_SRC
```

and the functions in our modified version [still assume this too](https://github.com/humacs/ii-pair/blob/f7d2283901b5a9ad62c4fcfa2792cc3fbd8d0f53/ii-ob-tmate.el#L199), under the hood.  

I think we will want to be able to specify the window through an explicit header-arg, so that the user doesn't have to type in their session every time, especially if their cooperation name is longer.  So we'll have to do some elisp codery to make sure we are grabbing the window from a passed in param in each case.

I worked today on understanding and customizing the code, and trying to set up the best dev loop for htis custom config, but do not have windows working yet.  i think I see the problem, but haven't designed the right solution yet.

**Comment by hh** [comment]
The title and work was for ob-tmux not ob-tmate. I was able to merge thing into our config here:

From https://github.com/ii/doom-config/commit/770dfacee21abf3712041e320b9d0a99b9d52a43
```
;; added to doom-config/config.el
(after! ii-pair
;;...
(setq
;;...
;; default to targeting the 'right eye'
   org-babel-default-header-args:tmux
  (:session . ,(if (getenv "SESSION_NAME")
                    (getenv "SESSION_NAME")
                  "org"))
)
```
From https://github.com/cloudnative-coop/coop-templates/blob/main/iipod/agent.tf#L43
```
# Added to coop-templates main/iipod/agent.tf
resource "coder_agent" "ii" {
 env = {
    SESSION_NAME        = "${lower(data.coder_workspace.ii.name)}"
    }
}
```

**Comment by hh** [comment]
@zachmandeville  can you verify this works and close with comment?

**Comment by hh** [comment]
Use https://coder.ii.nz/templates/iipod/workspace

**Comment by zachmandeville** [comment]
Tested and it works!  I think this issue can be closed.
